# Generated by Django 5.0.4 on 2024-12-15 04:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_userprofile_followers_count_and_more'),
        ('userarea', '0002_product_brand_name_product_slug_product_upload_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='Follow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('follower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='following', to='accounts.userprofile')),
                ('following', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followers', to='accounts.userprofile')),
            ],
            options={
                'indexes': [models.Index(fields=['follower', 'following'], name='userarea_fo_followe_91f440_idx')],
                'unique_together': {('follower', 'following')},
            },
        ),
    ]
