# Generated by Django 5.0.4 on 2024-08-30 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userarea', '0003_alter_product_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('draft', 'Draft'), ('reserved', 'Reserved'), ('sold', 'Sold')], default='active', max_length=10),
        ),
    ]
