# Generated by Django 5.0.4 on 2025-01-01 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userarea', '0004_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
