# Generated by Django 5.0.4 on 2025-01-03 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userarea', '0005_notification_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='icon_img',
            field=models.ImageField(blank=True, null=True, upload_to='category_icons/'),
        ),
    ]
