# Generated by Django 5.0.4 on 2024-12-12 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='offer',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
