# Generated by Django 5.0.4 on 2024-12-12 05:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatapp', '0002_alter_message_offer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='offer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='messages', to='chatapp.offer'),
        ),
    ]
