# Generated by Django 5.0.4 on 2025-01-03 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usersettings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='subject',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
